package com.shiva.emailTempBuilder;

public class EmailTemplateBuilder {

    /**
     * This HTML template defines a responsive, inline-styled email layout used for
     * delivering AI-generated daily news summaries.
     *
     * The template uses inline CSS to ensure consistent rendering across major
     * email clients such as Gmail, which restrict external stylesheets.
     *
     * It includes a branded header, a content card for news delivery, and a footer
     * indicating automated generation via AWS Lambda.
     *
     * The %s placeholder is dynamically replaced at runtime with formatted news
     * content generated by the AI service.
     *
     * UTF-8 encoding is used to support special characters and emojis within the
     * email body.
     */

    public static String buildNewsTemplate(String news) {

        return """
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>Daily News</title>
        </head>

        <body style="
            margin:0;
            padding:30px;
            background-color:white;
            font-family:Arial, Helvetica, sans-serif;
        ">

            <!-- Outer container -->
            <div style="
                max-width:900px;
                margin:auto;
                background-color:#456882;
                border-radius:12px;
                padding:28px;
                box-shadow:0 10px 30px rgba(0,0,0,0.6);
            ">

                <!-- Header -->
                <h2 style="
                    margin:0 0 10px 0;
                    text-align:center;
                    color:#f5c26b;
                    font-size:28px;
                    letter-spacing:1px;
                ">
                    AI News Bot
                </h2>

                <!-- Content card -->
                <div style="
                    background:#1B3C53;
                    border-radius:10px;
                    padding:25px;
                    color:#ffffff;
                ">

                    <h3 style="
                        margin-top:0;
                        color:#ffffff;
                        font-size:18px;
                    ">
                        Hello 👋
                    </h3>

                    <p style="
                        font-size:14px;
                        color:#e0e0e0;
                        margin-bottom:20px;
                    ">
                        Here are today’s <span style="color:#f5c26b;">Top 10 News Updates</span> curated just for you:
                    </p>

                    <!-- News content -->
                    <div style="
                        background-color:rgba(0,0,0,0.35);
                        padding:18px;
                        border-radius:8px;
                        white-space:pre-line;
                        font-size:14px;
                        line-height:1.7;
                        color:#ffffff;
                    ">
                        %s
                    </div>

                </div>

                <!-- Footer -->
                <hr style="
                    margin:30px 0;
                    border:none;
                    height:1px;
                    background:linear-gradient(to right,#f5c26b,#444,#f5c26b);
                ">

                <p style="
                    text-align:center;
                    font-size:12px;
                    color:#9a9a9a;
                    margin:0;
                ">
                    Generated automatically using AI via AWS Lambda
                </p>

            </div>

        </body>
        </html>
        """.formatted(news);
    }
}
